import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { 
    submitSDQAssessment,
    getStudentSDQAssessments,
    getStudentCareCases,
    getActiveParentToken
} from '../../services/careService';
import { useAuth } from '../../hooks/useAuth';
import { useLanguage } from '../../context/LanguageContext';
import Navbar from '../common/Navbar';
import SDQForm from './SDQForm';
import { Card, Button, LoadingSpinner } from '../ui';
import { toast } from 'react-hot-toast';
import { CheckCircle2, Home, Heart } from 'lucide-react';
import { getCurrentSchoolYear } from '../../utils/schoolYear';

export default function StudentSDQPage() {
    const { user: currentUser, logout } = useAuth();
    const { t } = useLanguage();
    const navigate = useNavigate();

    const [loading, setLoading] = useState(true);
    const [submitted, setSubmitted] = useState(false);
    const [isSubmitting, setIsSubmitting] = useState(false);
    const [parentLink, setParentLink] = useState('');

    useEffect(() => {
        const checkSubmissionStatus = async () => {
            try {
                if (!currentUser?.uid) return;

                const currentYear = getCurrentSchoolYear();

                // Fetch active parent token link if generated by the teacher
                const tokenData = await getActiveParentToken(currentUser.uid, currentYear);
                if (tokenData) {
                    setParentLink(tokenData.url);
                }

                // Check if student has already submitted SDQ for this year
                const assessments = await getStudentSDQAssessments(currentUser.uid, currentYear);
                const studentCompleted = assessments.some(a => a.informantType === 'student');

                if (studentCompleted) {
                    setSubmitted(true);
                }
            } catch (err) {
                console.error("Error loading StudentSDQPage:", err);
            } finally {
                setLoading(false);
            }
        };

        if (currentUser) {
            checkSubmissionStatus();
        }
    }, [currentUser]);

    const handleSubmitAssessment = async (responses, impactAssessment) => {
        setIsSubmitting(true);
        try {
            const currentYear = getCurrentSchoolYear();
            let careCaseId = null;
            
            // Find active case for current year
            const cases = await getStudentCareCases(currentUser.uid);
            const activeCase = cases.find(c => c.schoolYear === currentYear && c.status === 'active');
            if (activeCase) {
                careCaseId = activeCase.id;
            }

            const data = {
                studentId: currentUser.uid,
                careCaseId,
                schoolYear: currentYear,
                informantType: 'student',
                assessmentType: 'initial',
                responses,
                impactAssessment
            };
            await submitSDQAssessment(data, currentUser);
            setSubmitted(true);
            toast.success("ส่งแบบประเมินสำเร็จ!");
        } catch (err) {
            console.error("Error submitting student SDQ:", err);
            toast.error("เกิดข้อผิดพลาดในการส่งข้อมูล กรุณาลองใหม่อีกครั้ง");
        } finally {
            setIsSubmitting(false);
        }
    };

    const handleExit = async () => {
        try {
            await logout();
            navigate('/login');
            window.close();
        } catch (err) {
            console.error("Error logging out:", err);
        }
    };

    if (loading) {
        return (
            <div className="min-h-screen bg-slate-50">
                <Navbar showBack={true} />
                <div className="flex flex-col items-center justify-center py-32 gap-4">
                    <LoadingSpinner size="lg" />
                    <p className="text-slate-400 font-bold uppercase tracking-widest text-xs">
                        {t('loading')}
                    </p>
                </div>
            </div>
        );
    }

    if (submitted) {
        return (
            <div className="min-h-screen bg-slate-50">
                <Navbar showBack={false} />
                <div className="max-w-7xl mx-auto px-4 py-12">
                    <Card className="max-w-md mx-auto p-8 border border-emerald-100 shadow-xl shadow-slate-100 text-center">
                        <div className="w-16 h-16 bg-emerald-50 text-emerald-500 rounded-full flex items-center justify-center mx-auto mb-6 border border-emerald-100">
                            <CheckCircle2 size={32} />
                        </div>
                        <h2 className="text-xl font-black text-slate-800 mb-2 tracking-tight">
                            ส่งแบบประเมินเรียบร้อยแล้ว
                        </h2>
                        <p className="text-slate-500 text-sm leading-relaxed mb-6 font-semibold">
                            {t('sdq.studentPage.thankYou')}
                        </p>

                        {parentLink && (
                            <div className="mb-6 p-5 bg-rose-50 border border-rose-100 rounded-2xl text-left">
                                <h4 className="text-xs font-black text-rose-700 uppercase tracking-wider mb-1 flex items-center gap-1.5 font-bold">
                                    <Heart size={14} className="fill-rose-500 text-rose-700" />
                                    <span>ลิงก์แบบประเมินสำหรับผู้ปกครอง (SDQ-P)</span>
                                </h4>
                                <p className="text-[10px] text-rose-500 font-semibold mb-3 leading-relaxed">
                                    กรุณาส่งลิงก์นี้ให้ผู้ปกครองทำแบบประเมินคัดกรองออนไลน์:
                                </p>
                                <div className="flex items-center gap-2 bg-white border border-rose-200 rounded-xl p-2 pl-3 shadow-inner">
                                    <input
                                        type="text"
                                        readOnly
                                        value={parentLink}
                                        className="bg-transparent border-none outline-none text-xs text-slate-600 font-mono w-full select-all"
                                    />
                                    <button
                                        type="button"
                                        onClick={() => {
                                            navigator.clipboard.writeText(parentLink);
                                            toast.success("คัดลอกลิงก์ผู้ปกครองสำเร็จ!");
                                        }}
                                        className="px-3 py-1.5 bg-rose-50 hover:bg-rose-100 text-rose-600 rounded-lg text-xs font-bold transition-colors shrink-0 cursor-pointer"
                                    >
                                        คัดลอก
                                    </button>
                                </div>
                            </div>
                        )}

                        <div className="flex justify-center text-primary/30 mb-8">
                            <Heart size={24} className="animate-pulse fill-current" />
                        </div>
                        <div className="flex flex-col gap-3">
                            <Button 
                                variant="primary" 
                                onClick={handleExit}
                                className="w-full flex items-center justify-center gap-2"
                            >
                                <span>ออกจากระบบเพื่อออกจากโปรแกรม (Exit Program)</span>
                            </Button>
                            <Button 
                                variant="secondary" 
                                onClick={() => navigate('/student')}
                                className="w-full flex items-center justify-center gap-2 text-xs"
                            >
                                <Home size={16} />
                                <span>กลับหน้าแดชบอร์ดนักเรียน</span>
                            </Button>
                        </div>
                    </Card>
                </div>
            </div>
        );
    }

    return (
        <div className="min-h-screen bg-slate-50 pb-20">
            <Navbar showBack={true} />

            <div className="max-w-3xl mx-auto px-4 py-8 space-y-6">
                {parentLink && (
                    <div className="bg-gradient-to-r from-rose-500 to-pink-600 text-white rounded-3xl p-6 shadow-xl shadow-rose-100 border border-rose-400">
                        <h4 className="text-sm font-black tracking-wider uppercase mb-1 flex items-center gap-2 font-bold">
                            <Heart size={16} className="fill-current text-white" />
                            <span>แบบประเมินสำหรับผู้ปกครอง (SDQ-P)</span>
                        </h4>
                        <p className="text-xs text-rose-100 font-semibold mb-4 leading-relaxed">
                            เมื่อท่านทำแบบประเมินของนักเรียนเสร็จแล้ว กรุณาส่งลิงก์ด้านล่างนี้ให้ผู้ปกครองทำแบบประเมินผู้ปกครองด้วย
                        </p>
                        <div className="flex items-center gap-2 bg-white/10 backdrop-blur-md border border-white/20 rounded-2xl p-2 pl-4 shadow-inner">
                            <input
                                type="text"
                                readOnly
                                value={parentLink}
                                className="bg-transparent border-none outline-none text-xs text-white font-mono w-full select-all placeholder-white/50"
                            />
                            <button
                                type="button"
                                onClick={() => {
                                    navigator.clipboard.writeText(parentLink);
                                    toast.success("คัดลอกลิงก์ผู้ปกครองสำเร็จ!");
                                }}
                                className="px-4 py-2 bg-white text-rose-600 hover:bg-rose-50 rounded-xl font-bold text-xs transition-colors shrink-0 cursor-pointer"
                            >
                                คัดลอกลิงก์
                            </button>
                        </div>
                    </div>
                )}

                <div className="bg-white rounded-[2rem] shadow-xl shadow-slate-100 border border-slate-100 p-6 md:p-10">
                    <SDQForm
                        informantType="student"
                        studentName={currentUser?.name || currentUser?.displayName}
                        assessmentType="initial"
                        onSubmit={handleSubmitAssessment}
                        isSubmitting={isSubmitting}
                    />
                </div>
            </div>
        </div>
    );
}
